--
-- @lc app=leetcode.cn id=197 lang=mysql
--
-- [197] 上升的温度
--
-- https://leetcode.cn/problems/rising-temperature/description/
--
-- database
-- Easy (53.84%)
-- Likes:    518
-- Dislikes: 0
-- Total Accepted:    202.7K
-- Total Submissions: 377.2K
-- Testcase Example:  '{"headers": {"Weather": ["id", "recordDate", "temperature"]}, "rows": {"Weather": [[1, "2015-01-01", 10], [2, "2015-01-02", 25], [3, "2015-01-03", 20], [4, "2015-01-04", 30]]}}'
--
-- 
-- 
-- 表： Weather
-- 
-- 
-- +---------------+---------+
-- | Column Name   | Type    |
-- +---------------+---------+
-- | id            | int     |
-- | recordDate    | date    |
-- | temperature   | int     |
-- +---------------+---------+
-- id 是该表具有唯一值的列。
-- 该表包含特定日期的温度信息
-- 
-- 
-- 
-- 编写解决方案，找出与之前（昨天的）日期相比温度更高的所有日期的 id 。
-- 
-- 返回结果 无顺序要求 。
-- 
-- 结果格式如下例子所示。
-- 
-- 
-- 
-- 示例 1：
-- 
-- 
-- 输入：
-- Weather 表：
-- +----+------------+-------------+
-- | id | recordDate | Temperature |
-- +----+------------+-------------+
-- | 1  | 2015-01-01 | 10          |
-- | 2  | 2015-01-02 | 25          |
-- | 3  | 2015-01-03 | 20          |
-- | 4  | 2015-01-04 | 30          |
-- +----+------------+-------------+
-- 输出：
-- +----+
-- | id |
-- +----+
-- | 2  |
-- | 4  |
-- +----+
-- 解释：
-- 2015-01-02 的温度比前一天高（10 -> 25）
-- 2015-01-04 的温度比前一天高（20 -> 30）
-- 
-- 
-- 
--

-- @lc code=start
# Write your MySQL query statement below
SELECT w1.id AS Id
FROM Weather w1,Weather w2 
WHERE TIMESTAMPDIFF(day,w2.recordDate,w1.recordDate)=1 AND w1.Temperature>w2.Temperature;
-- @lc code=end

