--
-- @lc app=leetcode.cn id=577 lang=mysql
--
-- [577] 员工奖金
--
-- https://leetcode.cn/problems/employee-bonus/description/
--
-- database
-- Easy (69.25%)
-- Likes:    72
-- Dislikes: 0
-- Total Accepted:    54.6K
-- Total Submissions: 78.8K
-- Testcase Example:  '{"headers":{"Employee":["empId","name","supervisor","salary"],"Bonus":["empId","bonus"]},"rows":{"Employee":[[3,"Brad",null,4000],[1,"John",3,1000],[2,"Dan",3,2000],[4,"Thomas",3,4000]],"Bonus":[[2,500],[4,2000]]}}'
--
-- 表：Employee 
-- 
-- 
-- +-------------+---------+
-- | Column Name | Type    |
-- +-------------+---------+
-- | empId       | int     |
-- | name        | varchar |
-- | supervisor  | int     |
-- | salary      | int     |
-- +-------------+---------+
-- empId 是该表中具有唯一值的列。
-- 该表的每一行都表示员工的姓名和 id，以及他们的工资和经理的 id。
-- 
-- 
-- 
-- 
-- 表：Bonus
-- 
-- 
-- +-------------+------+
-- | Column Name | Type |
-- +-------------+------+
-- | empId       | int  |
-- | bonus       | int  |
-- +-------------+------+
-- empId 是该表具有唯一值的列。
-- empId 是 Employee 表中 empId 的外键(reference 列)。
-- 该表的每一行都包含一个员工的 id 和他们各自的奖金。
-- 
-- 
-- 
-- 
-- 编写解决方案，报告每个奖金 少于 1000 的员工的姓名和奖金数额。
-- 
-- 以 任意顺序 返回结果表。
-- 
-- 结果格式如下所示。
-- 
-- 
-- 
-- 示例 1：
-- 
-- 
-- 输入：
-- Employee table:
-- +-------+--------+------------+--------+
-- | empId | name   | supervisor | salary |
-- +-------+--------+------------+--------+
-- | 3     | Brad   | null       | 4000   |
-- | 1     | John   | 3          | 1000   |
-- | 2     | Dan    | 3          | 2000   |
-- | 4     | Thomas | 3          | 4000   |
-- +-------+--------+------------+--------+
-- Bonus table:
-- +-------+-------+
-- | empId | bonus |
-- +-------+-------+
-- | 2     | 500   |
-- | 4     | 2000  |
-- +-------+-------+
-- 输出：
-- +------+-------+
-- | name | bonus |
-- +------+-------+
-- | Brad | null  |
-- | John | null  |
-- | Dan  | 500   |
-- +------+-------+
-- 
--
-- @lc code=start
# Write your MySQL query statement below
SELECT name,bonus
FROM Employee LEFT JOIN Bonus
ON Employee.empId = Bonus.empId
WHERE bonus IS NULL OR bonus<1000;
-- @lc code=end

